rating/urls.py
from django.urls import path
from django_filters.views import FilterView

from rating import views
from rating.filters import SubjectFilter

app_name = 'rating'
urlpatterns = [
    path('', views.index, name='index'),
    path('search', FilterView.as_view(filterset_class=SubjectFilter, template_name='rating/search_subject.html'),
         name='search'),
    path('add_subject', views.AddSubjectView.as_view(), name='add_subject'),
    path('<int:pk>/subject', views.SubjectView.as_view(), name='subject'),
    path('<int:pk>/opinion', views.OpinionView.as_view(), name='opinion'),
    path('<int:pk>/opinion/modify', views.ModifyOpinionView.as_view(), name='modify_opinion'),
    path('register/', views.register, name='register'),
    path('<int:pk>/profile/', views.UserView.as_view(), name='user'),
    path('<int:pk>/subject/add_opinion', views.AddOpinionView.as_view(), name='add_opinion'),
    path('activate_subject', views.ActivateSubjectView.as_view(), name='activate_subject'),
]

subjects_rating_system/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('rating.urls')),
    path('account/', include('django.contrib.auth.urls')),
    path('admin/', admin.site.urls),
]

rating/models.py
from enum import Enum

from django.contrib.auth.models import User as AuthUser
from django.core.validators import MinValueValidator, MaxValueValidator
from django.db import models
import datetime

from django.db.models import Avg
from django.urls import reverse


class User(models.Model):
    basic_info = models.ForeignKey(AuthUser, on_delete=models.CASCADE)

    @property
    def avg_rating(self):
        return Opinion.objects.filter(user=self).aggregate(Avg('rating'))[
                   'rating__avg'] or 'Nie oceniłeś jeszcze żadnego przedmiotu'

    @property
    def number_of_opinions(self):
        return Opinion.objects.filter(user=self).count()

    def __str__(self):
        return self.basic_info.username


class Status(Enum):
    WAITING_FOR_CONFIRMATION = 'waiting_for_confirmation'
    ACCEPTED = 'accepted'


class Subject(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, null=True)
    fullname = models.CharField(max_length=100)
    shortcut = models.CharField(max_length=10)
    tutor = models.CharField(max_length=100)
    basic_info = models.TextField(max_length=300)
    status = models.CharField(choices=((tag.name, tag.value) for tag in Status), max_length=50,
                              default=Status.WAITING_FOR_CONFIRMATION.name)

    @property
    def rating(self):
        return self.opinion_set.all().aggregate(Avg('rating'))['rating__avg'] or 'Brak oceny'

    @property
    def number_of_opinions(self):
        return Opinion.objects.filter(subject=self).count()

    def get_absolute_url(self):
        return reverse('rating:subject', kwargs={'pk': self.pk})

    def whole_info(self):
        return f'{self.shortcut}\n{self.fullname}\n{self.tutor}\n{self.basic_info}'

    def __str__(self):
        return self.shortcut


class Opinion(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, null=True)
    subject = models.ForeignKey(Subject, on_delete=models.CASCADE)
    title = models.CharField(max_length=50)
    text = models.TextField(max_length=500)
    date = models.DateField(default=datetime.date.today)
    rating = models.IntegerField(validators=[MinValueValidator(1), MaxValueValidator(5)])
    last_edited = models.DateField(null=True)

    def get_absolute_url(self):
        return reverse('rating:opinion', kwargs={'pk': self.pk})

    def __str__(self):
        return self.title

rating/forms.py
from django import forms

from rating.models import Subject, Status


class InactiveSubjectForm(forms.Form):
    Inactive_Subjects = forms.MultipleChoiceField(choices=[])

    def __init__(self, *args, **kwargs):
        super(InactiveSubjectForm, self).__init__(*args, **kwargs)
        self.options = (
            (subject.id, f'{subject.shortcut} {subject.fullname} created by {subject.user.basic_info.username}')
            for subject in Subject.objects.all().filter(status=Status.WAITING_FOR_CONFIRMATION.value))
        self.fields['Inactive_Subjects'] = forms.MultipleChoiceField(widget=forms.CheckboxSelectMultiple,
                                                                     choices=self.options)

rating/views.py
import datetime

from django import forms
from django.contrib.auth.decorators import login_required
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.core.mail import send_mail
from django.shortcuts import render, redirect
from django.urls import reverse
from django.views import generic
from django.views.decorators.http import require_GET
from django.views.generic import FormView

from rating.filters import OpinionFilter
from rating.forms import InactiveSubjectForm
from rating.models import Subject, Opinion, User, Status


def find_subjects(request):
    subjects = Subject.objects.all().filter(status=Status.ACCEPTED.value)
    if request.GET.get('rating'):
        subjects = [subject for subject in subjects if
                    isinstance(subject.rating, float) and subject.rating > float(request.GET['rating'])]
    elif request.GET.get('number_of_opinions'):
        subjects = [subject for subject in subjects if
                    subject.number_of_opinions >= float(request.GET['number_of_opinions'])]
    print(subjects)
    return subjects


@require_GET
@login_required
def index(request):
    context = {'subjects': find_subjects(request),
               'logged_user': User.objects.filter(basic_info=request.user)[0],
               'opinions': Opinion.objects.all()}

    return render(request, 'rating/index.html', context)


class SubjectView(LoginRequiredMixin, UserPassesTestMixin, generic.DetailView):
    template_name = 'rating/subject.html'
    model = Subject

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        subject = Subject.objects.filter(pk=self.kwargs['pk'])[0]
        context['subject'] = subject
        qs = subject.opinion_set
        context['filter'] = OpinionFilter(self.request.GET, queryset=qs)
        print(context)
        return context

    def test_func(self):
        subject = Subject.objects.filter(pk=self.kwargs['pk'])[0]
        return subject.status == Status.ACCEPTED.value


class AddSubjectView(LoginRequiredMixin, generic.CreateView):
    template_name = 'rating/add_subject.html'
    model = Subject
    fields = ['fullname', 'shortcut', 'tutor', 'basic_info']

    def form_valid(self, form):
        user = User.objects.get(basic_info=self.request.user)
        form.instance.user = user
        if user.basic_info.is_staff:
            form.instance.status = Status.ACCEPTED.value
        else:
            form.instance.status = Status.WAITING_FOR_CONFIRMATION.value
        # send_mail(
        #     'Subject added successfully',
        #     f'You just added subject written down below:\n{form.instance.whole_info()}',
        #     'pik.konsultacje@gmail.com',
        #     [form.instance.user.basic_info.email],
        #     fail_silently=False
        # )
        return super().form_valid(form)

    def get_success_url(self):
        return reverse('rating:index')


class OpinionView(LoginRequiredMixin, generic.DetailView):
    template_name = 'rating/opinion.html'
    model = Opinion

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['logged_user'] = User.objects.get(basic_info=self.request.user)
        return context


class AddOpinionView(LoginRequiredMixin, generic.CreateView):
    template_name = 'rating/add_opinion.html'
    model = Opinion
    fields = ['title', 'text', 'date', 'rating']

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['subject'] = Subject.objects.get(pk=self.kwargs['pk'])
        return context

    def form_valid(self, form):
        form.instance.user = User.objects.filter(basic_info=self.request.user)[0]
        form.instance.subject = Subject.objects.get(pk=self.kwargs['pk'])
        return super().form_valid(form)


class ModifyOpinionView(LoginRequiredMixin, generic.UpdateView):
    template_name = 'rating/modify_opinion.html'
    model = Opinion
    fields = ['title', 'text', 'date', 'rating']

    def form_valid(self, form):
        form.instance.last_edited = datetime.date.today()
        return super().form_valid(form)


class SignUpForm(UserCreationForm):
    email = forms.EmailField(max_length=254, help_text='Required. Inform a valid email address.')

    class Meta:
        import django.contrib.auth.models as auth_model
        model = auth_model.User
        fields = ('username', 'email', 'password1', 'password2')


def register(request):
    if request.method == 'POST':
        form = SignUpForm(request.POST)
        if form.is_valid():
            basic_user = form.save()
            user = User(basic_info=basic_user)
            # user.basic_info.is_active = False
            user.basic_info.save()
            user.save()
            from django.db import connection
            print(connection.queries)
            return redirect('/account/login')
    else:
        form = SignUpForm()
    return render(request, 'registration/register.html', {'form': form})


class UserView(LoginRequiredMixin, generic.DetailView):
    template_name = 'rating/user.html'
    model = User

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        logged_user = User.objects.get(basic_info=self.request.user)
        context['opinions'] = Opinion.objects.filter(user=logged_user).order_by('date')[:5]
        return context


class ActivateSubjectView(LoginRequiredMixin, UserPassesTestMixin, FormView):
    template_name = 'rating/activate_subject.html'
    form_class = InactiveSubjectForm

    def form_valid(self, form):
        subjects_to_be_activated = form.cleaned_data.get('Inactive_Subjects')
        print(subjects_to_be_activated)
        for subject in Subject.objects.filter(pk__in=subjects_to_be_activated):
            subject.status = Status.ACCEPTED.value
            subject.save()
        return super().form_valid(form)

    def test_func(self):
        return self.request.user.is_staff

    def get_success_url(self):
        return reverse('rating:activate_subject')

templates/rating/activate_subject.html
{% extends "rating/base.html" %}
{% block title %}
    Add subject
{% endblock %}
{% block body %}
    {% load bootstrap4 %}

    <form method="post" style="text-align: center">
        {% csrf_token %}
        {% bootstrap_form form %}


        <div class="buttons">
            <input type="submit" value="Activate" class="btn btn-success">
            <a href="{% url 'rating:index' %}" class="btn btn-primary">Main page</a>
        </div>
    </form>

    {#    {% if subject_list  %}#}
    {#         <form action="{% url 'rating:activate_subject' %}" method="post">#}
    {#            {% csrf_token %}#}
    {#            {% for subject in subject_list %}#}
    {#                <input type="checkbox" name="{{ subject.shortcut }}" value={{ subject }} > {{ subject.fullname }} - created by {{ subject.user.basic_info.username }}<br>#}
    {#            {% endfor %}#}
    {#             <input type="submit" value="Activate" class="btn btn-success">#}
    {#        </form>#}
    {#    {% else %}#}
    {#        <div class="info">#}
    {#            <p>There is no subjects to activate!</p>#}
    {#        </div>#}
    {#    {% endif %}#}

    {#    <select>#}
    {#        {% for subject in subject_list %}#}
    {#            <option value="{% url 'rating:subject' subject.id %}"> {{ subject.fullname }} - {{ subject.tutor }}</option>#}
    {#        {% endfor %}#}
    {#    </select>#}

{% endblock %}

templates/rating/add_opinion.html
{% extends "rating/base.html" %}
{% block title %}
   Add opinion
{% endblock %}
{% block body %}
    {% load bootstrap4 %}

    <h1>{{ subject.shortcut }}</h1>
    <h2>Add opinion</h2>
        <form method="post">
        {% csrf_token %}
        {% bootstrap_form form %}

        <div class="buttons">
            <button type="submit" class="btn btn-primary">Add</button>
            <a href="{% url 'rating:index' %}" class="btn btn-danger">Back</a>
        </div>
    </form>
{% endblock %}

templates/rating/add_subject.html
{% extends "rating/base.html" %}
{% block title %}
   Add subject
{% endblock %}
{% block body %}
    {% load bootstrap4 %}

    <h2>Add subject</h2>
        <form method="post">
        {% csrf_token %}
        {% bootstrap_form form %}
        <div class="buttons">
            <button type="submit" class="btn btn-primary">Add</button>
            <a href="{% url 'rating:index' %}" class="btn btn-danger">Back</a>
        </div>
    </form>
{% endblock %}

templates/rating/base.html
<!DOCTYPE html>
<html lang="en">

<head>

    <title>
        {% block title %}
            Subject rating system
        {% endblock %}
    </title>
    {% load static %}
    <link rel="shortcut icon" type="image/png" href="{% static 'favicon.ico' %}"/>
    <link rel="stylesheet" type="text/css" href="{% static 'style.css' %}">
    {% load bootstrap4 %}
    {% bootstrap_css %}
    {% bootstrap_javascript jquery='full' %}
</head>
<body>

{% block body %}
{% endblock %}

</body>
{% block logout_button %}
    <div class="logout_button">
        <a href="{% url 'logout' %}" class="btn btn-danger"> Logout </a>
    </div>
{% endblock %}
</html>

templates/rating/index.html
{% extends "rating/base.html" %}



{% block title %}
    Main page
{% endblock %}
{% block body %}

    <h1>Subjects</h1>
    <br/>
    <form method="get">
        Mark
        <select name="rating">
            <option value=""></option>
            <option value="1">More than 1</option>
            <option value="2">More than 2</option>
            <option value="3">More than 3</option>
            <option value="4">More than 4</option>
            <option value="5">More than 5</option>
        </select>
        Number of opinions
        <select name="number_of_opinions">
            <option value=""></option>
            <option value="1">1 or more</option>
            <option value="5">5 or more</option>
            <option value="10">10 or more</option>
        </select>
        <input type="submit" value="Filter" class="btn btn-primary">
    </form>
    <div class="list-group">
        {% for subject in subjects %}
            <li class="list-group-item d-flex justify-content-between align-items-center">
                <a href="{% url 'rating:subject' subject.id %}" class="list-group-item list-group-item-action">
                    <p>{{ subject.fullname }} - {{ subject.tutor }}</p></a>
                <span class="badge badge-primary badge-pill">{{ subject.number_of_opinions }}</span>
            </li>
        {% endfor %}
    </div>

    <div class="buttons">
        <a href="{% url 'rating:user' logged_user.id %}" class="btn btn-primary">User info</a>
        <a href="{% url 'rating:add_subject' %}" class="btn btn-danger">Add subject</a>
    </div>
{% endblock %}

templates/rating/modify_opinion.html
{% extends "rating/base.html" %}
{% block title %}
    Opinion
{% endblock %}
{% block body %}
    {% load bootstrap4 %}

    <h1>{{ subject.shortcut }}</h1>
    <h2>Edit opinion</h2>
    <form method="post" class="form">
        {% csrf_token %}
        {% bootstrap_form form %}
        <div class="buttons">
            <button type="submit" class="btn btn-primary"> Edit</button>
            <a href="{% url 'rating:opinion' opinion.pk %}" class="btn btn-danger">Back</a>
        </div>
    </form>

{% endblock %}

templates/rating/opinion.html
{% extends "rating/base.html" %}
{% block title %}
    Opinion
{% endblock %}
{% block body %}

    <h1>{{ opinion.title }}</h1>
    <h2>{{ opinion.subject }}</h2>
    <h2> Creation: {{ opinion.date }}</h2>
    <h3>
        {% if opinion.last_edited %}
            Last edited: {{ opinion.last_edited }}
        {% endif %}
    </h3>
    <p>{{ opinion.text }}</p>
    <p>Mark: {{ opinion.rating }}</p>

    <div class="buttons">
        {% if logged_user == opinion.user %}
            <a href="{% url 'rating:modify_opinion' opinion.pk %}" class="btn btn-primary">Edit opinion</a>
        {% endif %}
        <a href="{% url 'rating:subject' opinion.subject.pk %}" class="btn btn-danger">Subject main page</a>
    </div>

{% endblock %}

templates/rating/search_subject.html
{% extends "rating/base.html" %}

{% block body %}
    <form method="get">
        {{ filter.form.as_p }}
        <button type="submit">Search</button>
    </form>
    <ul>
        {% for subject in filter.qs %}
            <li>{{ subject.shortcut }} - {{ subject.rating }}</li>
        {% endfor %}
    </ul>
{% endblock %}

templates/rating/subject.html
{% extends "rating/base.html" %}
{% block title %}
    {{ subject.shortcut }}
{% endblock %}
{% block body %}

    <h1>{{ subject.fullname }} - {{ subject.shortcut }}</h1>
    <h2>{{ subject.tutor }}</h2>
    <p>Info: {{ subject.basic_info }}</p>
    <p>Average mark: {{ subject.rating|floatformat:2 }} </p>

    <h3>Opinions:</h3>
    <form method="get">
        {{ filter.form.as_p }}
        <button type="submit" class="btn btn-primary">Filter</button>
    </form>
    {% for opinion in filter.qs %}
        <a href="{% url 'rating:opinion' opinion.id %}"
           class="list-group-item list-group-item-action align-items-center"> {{ opinion.title }}
            - {{ opinion.text|truncatechars:20 }} </a><br/>
    {% endfor %}

    <div class="buttons">
        <a href="{% url 'rating:index' %}" class="btn btn-primary">Main page</a>
        <a href="{% url 'rating:add_opinion' subject.id %}" class="btn btn-success">Add opinion</a>
    </div>


{% endblock %}

templates/rating/user.html
{% extends "rating/base.html" %}
{% block title %}
    User panel
{% endblock %}
{% block body %}
    <h1>Login: {{ user.basic_info.username }}</h1>
    <h2>Email: {{ user.basic_info.email }}</h2>
    <p>Opinions created - {{ user.number_of_opinions }}</p>
    <p>Average mark: {{ user.avg_rating|floatformat:2 }}</p>
    <p>Last opinions:</p>
    <div class="list-group">
        {% for opinion in opinions %}
            <a href="{% url 'rating:opinion' opinion.pk %}"
               class="list-group-item list-group-item-action align-items-center">{{ opinion.subject.shortcut }} - {{ opinion.title }} - {{ opinion.rating }}</a><br/>
        {% endfor %}
    </div>
    <div class="buttons">
        <a href="{% url 'rating:index' %}" class="btn btn-danger">Main page</a>
        {% if user.basic_info.is_staff %}
            <a href="{% url 'rating:activate_subject' %}" class="btn btn-primary">Inactive subjects</a>
        {% endif %}
    </div>
{% endblock %}